export enum Gouvernorat {
  TUNIS = 'TUNIS',
  ARIANA = 'ARIANA',
  BEN_AROUS = 'BEN_AROUS',
  MANOUBA = 'MANOUBA',
  NABEUL = 'NABEUL',
  BEJA = 'BEJA',
  JENDOUBA = 'JENDOUBA',
  BIZERTE = 'BIZERTE',
  SILIANA = 'SILIANA',
  KAIROUAN = 'KAIROUAN',
  KASSERINE = 'KASSERINE',
  SFAX = 'SFAX',
  SIDI_BOUZID = 'SIDI_BOUZID',
  GABES = 'GABES',
  MEDENINE = 'MEDENINE',
  TATAOUINE = 'TATAOUINE',
  GAFSA = 'GAFSA',
  TOZEUR = 'TOZEUR',
  KEBILI = 'KEBILI',
  MAHDIA = 'MAHDIA',
  MONASTIR = 'MONASTIR',
  SOUSSE = 'SOUSSE',
}

export enum Gender {
  HOMME = 'HOMME',
  FEMME = 'FEMME',
  AUTRE = 'AUTRE'
}

export enum Nationalite {
  TUNISIENNE = 'TUNISIENNE',
  FRANCAISE = 'FRANCAISE',
  AMERICAINE = 'AMERICAINE',
  ALLEMANDE = 'ALLEMANDE',
  ITALIENNE = 'ITALIENNE',
  MAROCAINE = 'MAROCAINE',
  CANADIENNE = 'CANADIENNE',
  ESPAGNOLE = 'ESPAGNOLE',
  ANGLAISE = 'ANGLAISE'
}
